FROM cblmariner.azurecr.io/base/core:1.0.20210127@sha256:08958790938a919e2a8fd1e4dfc3baf13f3b468d66b7fe3ec4b62686312aee6a

ADD configs/envoyproxy_io_proxy.yaml /etc/envoy/envoy.yaml

ARG ENVOY_BINARY_SUFFIX=_stripped
ADD linux/amd64/build_release${ENVOY_BINARY_SUFFIX}/* /usr/local/bin/

EXPOSE 10000

ENTRYPOINT ["envoy"]
CMD ["-c", "/etc/envoy/envoy.yaml"]
